const translations = {
  en: {
    app_title: "Life OS",
    app_subtitle: "Personal Life Manager",
    nav_dashboard: "Dashboard",
    nav_university: "University",
    nav_courses: "Courses",
    nav_calendar: "Time & Meetings",
    nav_gym: "Gym",
    nav_youtube: "YouTube",
    nav_settings: "Settings",
    sidebar_hint: "Single-user private workspace",
    header_title: "Your Life OS",
    header_subtitle: "Minimal, focused, and always in sync.",
    dashboard_title: "Dashboard",
    dashboard_subtitle: "Control center pulling data from every system.",
    dashboard_today: "Today",
    dashboard_today_tasks: "You have 2 tasks today.",
    dashboard_today_reminders: "2 active reminders.",
    dashboard_today_events: "Next event in 3 hours.",
    dashboard_reminders: "Active Reminders",
    badge_time: "Time",
    badge_study: "Study",
    badge_health: "Health",
    badge_university: "University",
    badge_learning: "Learning",
    reminder_lecture: "Lecture at 10:00.",
    reminder_study: "Time to study Course X.",
    reminder_gym: "No gym activity in 3 days.",
    dashboard_notifications: "Notification Center",
    dashboard_notifications_hint: "Reminders appear here and on the dashboard.",
    notification_exam: "Exam reminder: Discrete Math at 14:00.",
    notification_session: "Upcoming session: System Design at 18:30.",
    dashboard_summary: "Quick Summary",
    summary_study: "Study today: 2 hours planned.",
    summary_gym: "Gym this week: 3 sessions.",
    summary_youtube: "1 unfinished YouTube idea.",
    dashboard_sources: "Data Sources",
    dashboard_sources_desc: "Dashboard pulls from Calendar, University, Courses, Gym, and YouTube.",
    dashboard_overview: "System Overview",
    flow_calendar: "Central Calendar",
    flow_calendar_desc: "Collects university, courses, meetings, and personal events.",
    flow_reminders: "Reminder Engine",
    flow_reminders_desc: "Sends alerts to the dashboard and notification area.",
    flow_insights: "Smart Insights",
    flow_insights_desc: "Highlights study, gym, and YouTube progress.",
    dashboard_automation: "Automation Rules",
    automation_calendar: "All lectures, exams, study sessions, and meetings feed the calendar.",
    automation_reminders: "Reminder engine triggers time/date alerts across all pages.",
    automation_insights: "Smart summaries update study hours, gym streaks, and YouTube progress.",
    dashboard_quick_add: "Quick Add",
    quick_add_title: "Title",
    quick_add_title_placeholder: "Meeting with advisor",
    quick_add_date: "Date",
    quick_add_time: "Time",
    quick_add_type: "Type",
    quick_add_type_academic: "Academic",
    quick_add_type_learning: "Learning",
    quick_add_type_personal: "Personal",
    quick_add_save: "Save to Calendar",
    university_title: "University",
    university_subtitle: "Manage lectures, exams, and study days.",
    university_subjects: "Subjects",
    subject_data: "Data Structures",
    subject_ai: "AI Fundamentals",
    subject_math: "Discrete Math",
    university_schedule: "Schedules",
    university_schedule_desc: "Create lecture schedules, exam dates, and study sessions manually.",
    university_automation: "Automation",
    university_auto_reminders: "Auto reminders before lectures and exams.",
    university_auto_calendar: "All dates sync to the central calendar.",
    university_add: "Add Lecture / Exam",
    university_subject: "Subject",
    university_subject_placeholder: "Data Structures",
    university_type: "Type",
    university_type_lecture: "Lecture",
    university_type_exam: "Exam",
    university_type_study: "Study Day",
    university_date: "Date",
    university_time: "Time",
    university_add_button: "Add to Calendar",
    courses_title: "Courses & Self-Learning",
    courses_subtitle: "Track independent learning progress.",
    courses_plan: "Study Plan",
    courses_plan_desc: "Define course name, platform, and weekly plan.",
    courses_sessions: "Study Sessions",
    courses_session_example: "Tue · 1 hour · React Basics",
    courses_session_example_two: "Thu · 2 hours · System Design",
    courses_automation: "Automation",
    courses_hours: "Total study hours and weekly consistency.",
    courses_streak: "Study streak and missed session alerts.",
    courses_log: "Log Study Session",
    courses_course: "Course",
    courses_course_placeholder: "System Design",
    courses_platform: "Platform",
    courses_platform_placeholder: "YouTube",
    courses_duration: "Duration",
    courses_duration_placeholder: "1 hour",
    courses_date: "Date",
    courses_log_button: "Save Session",
    calendar_title: "Time & Meetings",
    calendar_subtitle: "Unified calendar for all events.",
    calendar_view: "Calendar View",
    calendar_view_desc: "All academic, learning, and personal events appear here.",
    calendar_event_one: "10:00 · Data Structures lecture",
    calendar_source_university: "University",
    calendar_event_two: "15:00 · Gym (Pull)",
    calendar_source_gym: "Gym",
    calendar_event_three: "19:00 · Script review",
    calendar_source_youtube: "YouTube",
    calendar_events: "Manual Events",
    calendar_events_example: "Meeting · Sun 5:00 PM",
    calendar_events_example_two: "Personal review · Wed 7:30 PM",
    calendar_reminders: "Reminder Engine",
    calendar_reminders_desc: "Time-based and date-based alerts connected to every page.",
    calendar_add: "Create Event",
    calendar_title_label: "Title",
    calendar_title_placeholder: "Mentor call",
    calendar_date: "Date",
    calendar_time: "Time",
    calendar_type: "Type",
    calendar_type_academic: "Academic",
    calendar_type_learning: "Learning",
    calendar_type_personal: "Personal",
    calendar_add_button: "Add Event",
    gym_title: "Gym & Fitness",
    gym_subtitle: "Track workouts and monitor progress.",
    gym_split: "Workout Split",
    gym_push: "Push",
    gym_pull: "Pull",
    gym_legs: "Legs",
    gym_entries: "Workout Entries",
    gym_entries_desc: "Log date, exercise name, weight, and notes.",
    gym_automation: "Automation",
    gym_frequency: "Monthly gym frequency and inactivity alerts.",
    gym_progress: "Weight progress per exercise and best stats.",
    gym_log: "Log Workout",
    gym_workout: "Workout",
    gym_exercise: "Exercise",
    gym_exercise_placeholder: "Bench press",
    gym_weight: "Weight",
    gym_weight_placeholder: "60 kg",
    gym_notes: "Notes",
    gym_notes_placeholder: "Felt strong",
    gym_log_button: "Save Workout",
    youtube_title: "YouTube Content",
    youtube_subtitle: "From idea to published video.",
    youtube_stage_ideas: "Stage 1 · Ideas",
    youtube_idea_example: "\"Minimal desk setup\" · Tech",
    youtube_idea_example_two: "\"Study with me\" · Lifestyle",
    youtube_stage_prep: "Stage 2 · Preparation",
    youtube_prep_script: "Script: 2 drafts pending.",
    youtube_prep_edit: "Editing: 1 video in progress.",
    youtube_stage_published: "Stage 3 · Published",
    youtube_published_desc: "Archive publish date, link, and notes.",
    youtube_add: "Add Idea",
    youtube_title_label: "Idea Title",
    youtube_title_placeholder: "Productivity routine",
    youtube_category: "Category",
    youtube_category_placeholder: "Productivity",
    youtube_description: "Description",
    youtube_description_placeholder: "Short summary",
    youtube_add_button: "Save Idea",
    settings_title: "Settings",
    settings_subtitle: "Personalize reminders and UI preferences.",
    settings_language: "Language",
    settings_language_desc: "Toggle between Arabic and English.",
    settings_notifications: "Reminder Preferences",
    settings_notifications_desc: "Adjust notification timing and channels.",
    settings_ui: "UI Preferences",
    settings_ui_desc: "Choose compact or spacious layout.",
    settings_controls: "Personalization",
    settings_reminder_window: "Reminder window",
    settings_reminder_30: "30 minutes before",
    settings_reminder_60: "1 hour before",
    settings_reminder_day: "1 day before",
    settings_density: "UI density",
    settings_density_comfort: "Comfortable",
    settings_density_compact: "Compact",
    settings_save: "Save Settings"
  },
  ar: {
    app_title: "لايف أو إس",
    app_subtitle: "مدير الحياة الشخصي",
    nav_dashboard: "لوحة التحكم",
    nav_university: "الجامعة",
    nav_courses: "الدورات",
    nav_calendar: "الوقت والاجتماعات",
    nav_gym: "النادي الرياضي",
    nav_youtube: "يوتيوب",
    nav_settings: "الإعدادات",
    sidebar_hint: "مساحة خاصة لمستخدم واحد",
    header_title: "نظام حياتك",
    header_subtitle: "بسيط، مركز، ومتزامن دائمًا.",
    dashboard_title: "لوحة التحكم",
    dashboard_subtitle: "مركز السيطرة الذي يجمع كل البيانات.",
    dashboard_today: "اليوم",
    dashboard_today_tasks: "لديك مهمتان اليوم.",
    dashboard_today_reminders: "تذكيران نشطان.",
    dashboard_today_events: "الحدث القادم بعد 3 ساعات.",
    dashboard_reminders: "التذكيرات النشطة",
    badge_time: "وقت",
    badge_study: "دراسة",
    badge_health: "صحة",
    badge_university: "الجامعة",
    badge_learning: "تعلم",
    reminder_lecture: "محاضرة الساعة 10:00.",
    reminder_study: "حان وقت دراسة الدورة X.",
    reminder_gym: "لا يوجد نشاط رياضي منذ 3 أيام.",
    dashboard_notifications: "مركز التنبيهات",
    dashboard_notifications_hint: "التذكيرات تظهر هنا وعلى لوحة التحكم.",
    notification_exam: "تذكير اختبار: رياضيات متقطعة الساعة 14:00.",
    notification_session: "جلسة قادمة: تصميم الأنظمة الساعة 18:30.",
    dashboard_summary: "ملخص سريع",
    summary_study: "الدراسة اليوم: ساعتان مخططتان.",
    summary_gym: "النادي هذا الأسبوع: 3 جلسات.",
    summary_youtube: "فكرة يوتيوب غير مكتملة.",
    dashboard_sources: "مصادر البيانات",
    dashboard_sources_desc: "اللوحة تسحب من التقويم والجامعة والدورات والنادي ويوتيوب.",
    dashboard_overview: "نظرة عامة للنظام",
    flow_calendar: "التقويم المركزي",
    flow_calendar_desc: "يجمع أحداث الجامعة والدورات والاجتماعات والشخصية.",
    flow_reminders: "محرك التذكير",
    flow_reminders_desc: "يرسل التنبيهات إلى اللوحة ومنطقة الإشعارات.",
    flow_insights: "رؤى ذكية",
    flow_insights_desc: "تُظهر تقدم الدراسة والنادي ويوتيوب.",
    dashboard_automation: "قواعد الأتمتة",
    automation_calendar: "كل المحاضرات والاختبارات وجلسات الدراسة والاجتماعات تنتقل للتقويم.",
    automation_reminders: "محرك التذكير يطلق تنبيهات زمنية وتاريخية عبر كل الصفحات.",
    automation_insights: "الملخصات الذكية تحدّث ساعات الدراسة وسلسلة النادي وتقدم يوتيوب.",
    dashboard_quick_add: "إضافة سريعة",
    quick_add_title: "العنوان",
    quick_add_title_placeholder: "اجتماع مع المرشد",
    quick_add_date: "التاريخ",
    quick_add_time: "الوقت",
    quick_add_type: "النوع",
    quick_add_type_academic: "أكاديمي",
    quick_add_type_learning: "تعلم",
    quick_add_type_personal: "شخصي",
    quick_add_save: "حفظ في التقويم",
    university_title: "الجامعة",
    university_subtitle: "إدارة المحاضرات والاختبارات وأيام الدراسة.",
    university_subjects: "المواد",
    subject_data: "هياكل البيانات",
    subject_ai: "أساسيات الذكاء الاصطناعي",
    subject_math: "رياضيات متقطعة",
    university_schedule: "الجداول",
    university_schedule_desc: "أنشئ جداول المحاضرات والاختبارات وجلسات الدراسة يدويًا.",
    university_automation: "الأتمتة",
    university_auto_reminders: "تذكيرات تلقائية قبل المحاضرات والاختبارات.",
    university_auto_calendar: "كل المواعيد تتزامن مع التقويم المركزي.",
    university_add: "إضافة محاضرة / اختبار",
    university_subject: "المادة",
    university_subject_placeholder: "هياكل البيانات",
    university_type: "النوع",
    university_type_lecture: "محاضرة",
    university_type_exam: "اختبار",
    university_type_study: "يوم دراسة",
    university_date: "التاريخ",
    university_time: "الوقت",
    university_add_button: "إضافة إلى التقويم",
    courses_title: "الدورات والتعلم الذاتي",
    courses_subtitle: "تتبع تقدم التعلم المستقل.",
    courses_plan: "خطة الدراسة",
    courses_plan_desc: "حدد اسم الدورة والمنصة والخطة الأسبوعية.",
    courses_sessions: "جلسات الدراسة",
    courses_session_example: "الثلاثاء · ساعة واحدة · أساسيات رياكت",
    courses_session_example_two: "الخميس · ساعتان · تصميم الأنظمة",
    courses_automation: "الأتمتة",
    courses_hours: "إجمالي ساعات الدراسة والانتظام الأسبوعي.",
    courses_streak: "سلسلة الدراسة والتنبيه عند تفويت الجلسات.",
    courses_log: "تسجيل جلسة دراسة",
    courses_course: "الدورة",
    courses_course_placeholder: "تصميم الأنظمة",
    courses_platform: "المنصة",
    courses_platform_placeholder: "يوتيوب",
    courses_duration: "المدة",
    courses_duration_placeholder: "ساعة واحدة",
    courses_date: "التاريخ",
    courses_log_button: "حفظ الجلسة",
    calendar_title: "الوقت والاجتماعات",
    calendar_subtitle: "تقويم موحد لكل الأحداث.",
    calendar_view: "عرض التقويم",
    calendar_view_desc: "جميع الأحداث الأكاديمية والتعلمية والشخصية تظهر هنا.",
    calendar_event_one: "10:00 · محاضرة هياكل البيانات",
    calendar_source_university: "الجامعة",
    calendar_event_two: "15:00 · النادي (سحب)",
    calendar_source_gym: "النادي",
    calendar_event_three: "19:00 · مراجعة السيناريو",
    calendar_source_youtube: "يوتيوب",
    calendar_events: "أحداث يدوية",
    calendar_events_example: "اجتماع · الأحد 5:00 مساءً",
    calendar_events_example_two: "مراجعة شخصية · الأربعاء 7:30 مساءً",
    calendar_reminders: "محرك التذكير",
    calendar_reminders_desc: "تنبيهات زمنية وتاريخية مرتبطة بكل الصفحات.",
    calendar_add: "إنشاء حدث",
    calendar_title_label: "العنوان",
    calendar_title_placeholder: "مكالمة مع المرشد",
    calendar_date: "التاريخ",
    calendar_time: "الوقت",
    calendar_type: "النوع",
    calendar_type_academic: "أكاديمي",
    calendar_type_learning: "تعلم",
    calendar_type_personal: "شخصي",
    calendar_add_button: "إضافة الحدث",
    gym_title: "النادي الرياضي واللياقة",
    gym_subtitle: "تتبع التمارين ومراقبة التقدم.",
    gym_split: "تقسيم التمرين",
    gym_push: "دفع",
    gym_pull: "سحب",
    gym_legs: "أرجل",
    gym_entries: "سجلات التمرين",
    gym_entries_desc: "سجل التاريخ واسم التمرين والوزن والملاحظات.",
    gym_automation: "الأتمتة",
    gym_frequency: "تكرار شهري وتنبيهات عدم النشاط.",
    gym_progress: "تقدم الأوزان وأفضل الأرقام.",
    gym_log: "تسجيل تمرين",
    gym_workout: "التمرين",
    gym_exercise: "التمرين",
    gym_exercise_placeholder: "ضغط صدر",
    gym_weight: "الوزن",
    gym_weight_placeholder: "60 كجم",
    gym_notes: "ملاحظات",
    gym_notes_placeholder: "شعرت بقوة",
    gym_log_button: "حفظ التمرين",
    youtube_title: "محتوى يوتيوب",
    youtube_subtitle: "من الفكرة إلى النشر.",
    youtube_stage_ideas: "المرحلة 1 · أفكار",
    youtube_idea_example: "\"إعداد مكتب بسيط\" · تقنية",
    youtube_idea_example_two: "\"ادرس معي\" · أسلوب حياة",
    youtube_stage_prep: "المرحلة 2 · التحضير",
    youtube_prep_script: "السيناريو: مسودتان بانتظار الإكمال.",
    youtube_prep_edit: "التحرير: فيديو واحد قيد العمل.",
    youtube_stage_published: "المرحلة 3 · منشور",
    youtube_published_desc: "أرشفة تاريخ النشر والرابط والملاحظات.",
    youtube_add: "إضافة فكرة",
    youtube_title_label: "عنوان الفكرة",
    youtube_title_placeholder: "روتين الإنتاجية",
    youtube_category: "الفئة",
    youtube_category_placeholder: "إنتاجية",
    youtube_description: "الوصف",
    youtube_description_placeholder: "ملخص قصير",
    youtube_add_button: "حفظ الفكرة",
    settings_title: "الإعدادات",
    settings_subtitle: "تخصيص التذكيرات وتفضيلات الواجهة.",
    settings_language: "اللغة",
    settings_language_desc: "التبديل بين العربية والإنجليزية.",
    settings_notifications: "تفضيلات التذكير",
    settings_notifications_desc: "تعديل توقيت الإشعارات والقنوات.",
    settings_ui: "تفضيلات الواجهة",
    settings_ui_desc: "اختيار تخطيط مدمج أو واسع.",
    settings_controls: "التخصيص",
    settings_reminder_window: "نافذة التذكير",
    settings_reminder_30: "قبل 30 دقيقة",
    settings_reminder_60: "قبل ساعة",
    settings_reminder_day: "قبل يوم",
    settings_density: "كثافة الواجهة",
    settings_density_comfort: "مريح",
    settings_density_compact: "مدمج",
    settings_save: "حفظ الإعدادات"
  }
};

const langToggle = document.getElementById("lang-toggle");
const navButtons = document.querySelectorAll(".nav__item");
const sections = document.querySelectorAll(".section");
const dateEl = document.getElementById("today-date");
const timeEl = document.getElementById("current-time");

let currentLang = "en";

const setLanguage = (lang) => {
  currentLang = lang;
  const textElements = document.querySelectorAll("[data-i18n]");
  textElements.forEach((el) => {
    const key = el.getAttribute("data-i18n");
    el.textContent = translations[lang][key] || el.textContent;
  });

  const placeholderElements = document.querySelectorAll("[data-i18n-placeholder]");
  placeholderElements.forEach((el) => {
    const key = el.getAttribute("data-i18n-placeholder");
    el.setAttribute("placeholder", translations[lang][key] || el.getAttribute("placeholder"));
  });

  document.documentElement.lang = lang;
  document.documentElement.dir = lang === "ar" ? "rtl" : "ltr";
  langToggle.textContent = lang === "ar" ? "EN" : "AR";
};

const setActiveSection = (sectionId) => {
  sections.forEach((section) => {
    section.classList.toggle("is-active", section.id === sectionId);
  });
  navButtons.forEach((button) => {
    button.classList.toggle("is-active", button.dataset.section === sectionId);
  });
};

const updateTime = () => {
  const now = new Date();
  dateEl.textContent = now.toLocaleDateString(currentLang === "ar" ? "ar-EG" : "en-US", {
    weekday: "long",
    month: "short",
    day: "numeric"
  });
  timeEl.textContent = now.toLocaleTimeString(currentLang === "ar" ? "ar-EG" : "en-US", {
    hour: "2-digit",
    minute: "2-digit"
  });
};

navButtons.forEach((button) => {
  button.addEventListener("click", () => {
    setActiveSection(button.dataset.section);
  });
});

langToggle.addEventListener("click", () => {
  setLanguage(currentLang === "en" ? "ar" : "en");
  updateTime();
});

setLanguage(currentLang);
updateTime();
setInterval(updateTime, 1000 * 60);
